name: 2. Demostración Trampa (Bloqueo automático)

on:
  workflow_dispatch: # Botón manual

jobs:
  escaneo-trampa:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Preparar Docker
        uses: docker/setup-buildx-action@v3

      - name: 3. Construir imagen (Código Vulnerable)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.vulnerable 
          push: false 
          load: true 
          tags: app-trampa:latest

      - name: 4. Escáner Trivy (Debe marcar X roja)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'app-trampa:latest'
          format: 'table'
          exit-code: '1' 
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'