name: Mejora Continua (Seguridad)
 
# ¿Cuándo se va a ejecutar?

on:

  push:

    branches: [ "master", "main" ]

  workflow_dispatch: # ¡Esto agrega un botón en GitHub para ejecutarlo manual frente al profe!
 
jobs:

  escaneo-seguridad:

    runs-on: ubuntu-latest

    steps:

      - name: 1. Descargar el código del repositorio

        uses: actions/checkout@v4
 
      - name: 2. Preparar el motor de Docker

        uses: docker/setup-buildx-action@v3
 
      - name: 3. Construir imagen (Fase de Build)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.vulnerable # <--- CAMBIO 1: Apunta al archivo trampa
          push: false 
          load: true 
          tags: prueba-seguridad:latest

      - name: 4. Capa DevSecOps - Escáner Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'prueba-seguridad:latest'
          format: 'table'
          exit-code: '1' # <--- CAMBIO 2: El '1' fuerza al sistema a fallar y detenerse
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'